---
title: "project_draft"
author: "Zayd Abdalla"
date: "5/10/2021"
output: word_document
---
```{r packages, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(mosaic)
library(mosaicData)
library(tidyverse)
library(tidymodels)
library(tidyquant)
library(estimatr)
library(gcookbook)
library(ggthemes)
library(kknn)
library(glmnet)
library(lubridate)
library(scales)
library(patchwork)
library(hrbrthemes)
library(kableExtra)
```

```{r merging_data, include=FALSE, warning=FALSE, message=FALSE}
####Warning: Fairly ram heavy, 25 million observations across 2 data sets
#load monthly data for spring 2020
yellow_tripdata_2020.03 <- read.csv("D:/DM FINAL/Data/yellow_tripdata_2020-03.csv")
yellow_tripdata_2020.04 <- read.csv("D:/DM FINAL/Data/yellow_tripdata_2020-04.csv")
yellow_tripdata_2020.05 <- read.csv("D:/DM FINAL/Data/yellow_tripdata_2020-05.csv")

#merge datasets
spring_20_nyc_taxi <- rbind(yellow_tripdata_2020.03, yellow_tripdata_2020.04, yellow_tripdata_2020.05)

#write to csv
write_csv(spring_20_nyc_taxi, "spring_20_nyc_taxi.csv")

#clear environment to save RAM space
rm(yellow_tripdata_2020.03)
rm(yellow_tripdata_2020.04)
rm(yellow_tripdata_2020.05)
rm(spring_20_nyc_taxi)

###repeat for spring 2019 data

#load monthly data for spring 2020
yellow_tripdata_2019.03 <- read.csv("D:/DM FINAL/Data/yellow_tripdata_2019-03.csv")
yellow_tripdata_2019.04 <- read.csv("D:/DM FINAL/Data/yellow_tripdata_2019-04.csv")
yellow_tripdata_2019.05 <- read.csv("D:/DM FINAL/Data/yellow_tripdata_2019-05.csv")

#merge datasets
spring_19_nyc_taxi <- rbind(yellow_tripdata_2019.03, yellow_tripdata_2019.04, yellow_tripdata_2019.05)

#write to csv
write_csv(spring_19_nyc_taxi, "spring_19_nyc_taxi.csv")

#clear environment to save RAM space
rm(yellow_tripdata_2019.03)
rm(yellow_tripdata_2019.04)
rm(yellow_tripdata_2019.05)
rm(spring_19_nyc_taxi)
```


```{r load_2019, message=FALSE, warning=FALSE}
#Confirmation that we can load merged data 
spring_19_nyc_taxi <- read.csv("D:/DM FINAL/Data/spring_19_nyc_taxi.csv")
#Add duration column
start <- ymd_hms(spring_19_nyc_taxi$tpep_pickup_datetime,tz=Sys.timezone())
end <- ymd_hms(spring_19_nyc_taxi$tpep_dropoff_datetime,tz=Sys.timezone())
diff <- end-start
duration <- as.duration(diff) #in seconds
spring_19_nyc_taxi$duration <- duration
```

```{r load_2020, message=FALSE, warning=FALSE}
#Confirmation that we can load merged data 
spring_20_nyc_taxi <- read.csv("D:/DM FINAL/Data/spring_20_nyc_taxi.csv")
#Add duration column
start <- ymd_hms(spring_20_nyc_taxi$tpep_pickup_datetime,tz=Sys.timezone())
end <- ymd_hms(spring_20_nyc_taxi$tpep_dropoff_datetime,tz=Sys.timezone())
diff <- end-start
duration <- as.duration(diff) #in seconds
spring_20_nyc_taxi$duration <- duration
pickup_time <- hour(start)
spring_20_nyc_taxi$pickup_time <- pickup_time
```


##2020 Exploration
```{r 2020 Exploration, message=FALSE}
###Summary stats
spring_20_nyc_taxi %>%
  mutate(Wkdays = wday(tpep_pickup_datetime, label = TRUE)) %>%
  ggplot() + 
  geom_bar(aes(x = Wkdays), fill = "green", color = "gold" ) +
 scale_y_continuous(labels = comma) +facet_wrap(month(spring_20_nyc_taxi$tpep_pickup_datetime, label = TRUE))
```
```{r, warning=FALSE, message = FALSE}
spring_20_nyc_taxi %>%
  mutate(hour = hour(tpep_pickup_datetime, label = TRUE)) %>%
  ggplot() + 
  geom_bar(aes(x = hour), fill = "green", color = "gold" ) +
 scale_y_continuous(labels = comma) 
```

```{r}
spring_20_nyc_taxi %>%
  mutate(day_of_week = factor(tpep_pickup_datetime,
                              levels = c("Mon", "Tue", "Wed","Thu",
                                         "Fri","Sat","Sun")),
         month = factor(month, levels = c("Mar", "Apr","May")))
Figure1 <- 
  spring_20_nyc_taxi %>%
  group_by(hour_of_day, day_of_week, month) %>%
  mutate(avg_boarding = mean(boarding)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x = hour_of_day, y = avg_boarding, color = month)) +
  scale_x_continuous(expand = c(0,0), limits = c(0, 24), 
                     breaks = seq(10, 20, 5)) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 200)) +
  scale_color_ft("Month") +
  facet_wrap(. ~ day_of_week, scales = "free") + 
  labs(x = "Hour of day", y = "Average boarding",
       title = "Average bus ridership around UT",
       subtitle = "Tracked by Optical Scanner",
       caption = "Source: Capital Metro") + 
  theme_ipsum(grid = "XY", axis = "xy") 
```

```{r}
set.seed(300)
sample_20 <- sample(spring_20_nyc_taxi, 50000, replace = TRUE)

spring_20_split <- initial_split(sample_20, strata = "total_amount", prop = 0.75)
spring_20_train <- training(spring_20_split)
spring_20_test  <- testing(spring_20_split)
dim(spring_20_train)
dim(spring_20_test)
rm(spring_20_nyc_taxi)


#use cross-validation to split training set into k-folds.
# 3 fold cross validation 
taxi_fold20 <- vfold_cv(spring_20_train, v = 3, repeats = 1, strata = "total_amount")

lm_spec20 <-
  linear_reg() %>%
  set_mode("regression") %>%
  set_engine("lm")
lm_spec20

knn_spec20 <-
  nearest_neighbor(
    mode = "regression",
    neighbors = tune("K"),
  ) %>%
  set_engine("kknn")
knn_spec20
```

  
  
```{r, warning=FALSE, cache=TRUE, message=FALSE}
# feature engineering
taxi_wf20 <-
  workflow() %>%
  add_formula(total_amount ~ passenger_count + duration + trip_distance ++fare_amount +extra + mta_tax + tip_amount + tolls_amount + congestion_surcharge + improvement_surcharge) %>%
  # log total amount
  step_log(total_amount)
taxi_wf20
```

```{r, warning=FALSE, message=FALSE}
#Fitting LM model

set.seed(400)
lm_rs20 <- 
  taxi_wf20 %>%
  add_model(lm_spec20) %>%
  fit_resamples(
    resamples = taxi_fold20,
    control = control_resamples(save_pred = TRUE)
  )


#Fitting KNN model


set.seed(400)
# feature engineering
knn_recipe20 <- 
  recipe(total_amount ~ passenger_count + duration + trip_distance ++fare_amount +extra + mta_tax + tip_amount + tolls_amount + congestion_surcharge + improvement_surcharge, data = spring_20_train) %>%
  # log total_amount
  step_log(total_amount) 

# workflow
knn_wf20 <- 
  workflow() %>%
  add_model(knn_spec20) %>%
  add_recipe(knn_recipe20)

# hyperparameter tuning
gridvals20 <- tibble(K = seq(1, 100)) 

knn_rs20 <- 
  knn_wf20 %>%
  tune_grid(
    resamples = taxi_fold20,
    grid = gridvals20,
    control = control_resamples(save_pred = TRUE)) 
knn_rs20

set.seed(400)

# Display only minimum RMSE
knn_min20 <- knn_rs20 %>%
  collect_metrics() %>% 
  filter(.metric == "rmse") %>%
  filter(mean == min(mean))
knn_min20
```

```{r message=FALSE, warning=FALSE}
## Evaluate Models

# Evaluate Linear Model
final_lm_wf20 <- 
  taxi_wf20 %>%
  add_model(lm_spec) 
  
lm_fit20 <- 
  final_lm_wf20 %>%
  last_fit(split = spring_20_split)
lm_fit20 %>% collect_metrics()

lm_results20 <-
  lm_fit20 %>%
  collect_predictions()
# view results
lm_results20


lm_fit20$.workflow[[1]] %>% 
  tidy() %>% 
  kable(digits = 4, "pipe") 
```

```{r}
# LM Graphically
lm_results20 %>%
  ggplot(aes(.pred, total_amount)) +  #.pred?
  geom_abline(lty = 2, color = "black", size = 1) +
  geom_point(alpha = 0.5, color = "dark green") +
  labs(
    title = 'Linear Regression Results',
    x = "Truth",
    y = "Predicted total amount",
    color = NULL
  ) + 
  theme_ipsum()
```

```{r}
# Evaluate KNN Model

final_knn_wf20 <- 
  taxi_wf20%>% 
  finalize_workflow(knn_min20)

knn_fit20 <- 
  final_knn_wf20 %>% 
  last_fit(split = spring_20_split)

knn_fit20 %>% collect_metrics()

# predictions
knn_results20 <- 
  knn_fit20 %>% 
  collect_predictions()
# view results
knn_results20

# KNN Graphically
knn_results20 %>%
  ggplot(aes(.pred, total_amount)) +
  geom_abline(lty = 2, color = "black", size = 1) +
  geom_point(alpha = 0.5, color = "dark green") +
  labs(
    title = 'KNN Regression Results',
    x = "Truth",
    y = "Predicted total amount",
    color = NULL
  ) + 
  theme_ipsum()
```



##2019 Exporation
```{r}
spring_19_nyc_taxi %>%
  mutate(month = month(tpep_pickup_datetime, label = TRUE)) %>%
  ggplot() + 
  geom_bar(aes(x = month), fill = "green", color = "gold" ) +
 scale_y_continuous(labels = comma)
```


```{r}
set.seed(300)

spring_19_split <- initial_split(spring_19_nyc_taxi, strata = "total_amount", prop = 0.75)
spring_19_train <- training(spring_19_split)
spring_19_test  <- testing(spring_19_split)
dim(spring_19_train)
dim(spring_19_test)

#use cross-validation to split training set into k-folds.
# 3 fold cross validation 
taxi_fold19 <- vfold_cv(spring_19_train, v = 3, repeats = 1, strata = "total_amount")

lm_spec19 <-
  linear_reg() %>%
  set_mode("regression") %>%
  set_engine("lm")
lm_spec19

knn_spec19 <-
  nearest_neighbor(
    mode = "regression",
    neighbors = tune("K"),
  ) %>%
  set_engine("kknn")
knn_spec19
```

```{r}
taxi_wf19 <-
  workflow() %>%
  add_formula(total_amount ~ .) %>%
  # log total amount
  step_log(total_amount) %>%
  # mean impute numeric variables
  step_impute_mean(all_numeric(), -all_outcomes()) %>%
  # rescale all numeric variables to lie between 0 and 1
  step_range(all_numeric(), min = 0, max = 1) %>%
  # one-hot
  step_dummy(store_and_fwd_flag) %>%
  # remove predictor variables that are almost the same for every entry
  step_nzv(all_predictors()) 
```


```{r}
# workflow
knn_wf19 <- 
  workflow() %>%
  add_model(knn_spec19) %>%
  add_recipe(knn_recipe19)

# hyperparameter tuning
gridvals19 <- tibble(K = seq(1, 200)) #why 200?

knn_rs19 <- 
  knn_wf19 %>%
  tune_grid(
    resamples = taxi_fold19,
    grid = gridvals19,
    control = control_resamples(save_pred = TRUE)) 
knn_rs19

set.seed(400)

# Display only minimum RMSE
knn_min19 <- knn_rs19 %>%
  collect_metrics() %>% 
  filter(.metric == "rmse") %>%
  filter(mean == min(mean))
knn_min19


```

```{r message=FALSE, warning=FALSE}
## Evaluate Models

# Evaluate Linear Model
final_lm_wf19 <- 
  taxi_wf19 %>%
  add_model(lm_spec19) 
  
lm_fit19 <- 
  final_lm_wf19 %>%
  last_fit(split = spring_19_split)
lm_fit19 %>% collect_metrics()

lm_results19 <-
  lm_fit19 %>%
  collect_predictions()
# view results
lm_results19


lm_fit19$.workflow[[1]] %>% 
  tidy() %>% 
  kable(digits = 4, "pipe") 
```

```{r}
# LM Graphically
lm_results19 %>%
  ggplot(aes(.pred, total_amount)) +  #.pred?
  geom_abline(lty = 2, color = "black", size = 1) +
  geom_point(alpha = 0.5, color = "dark green") +
  labs(
    title = 'Linear Regression Results',
    x = "Truth",
    y = "Predicted total amount",
    color = NULL
  ) + 
  theme_ipsum()
```

```{r}
# Evaluate KNN Model

final_knn_wf19 <- 
  taxi_wf19%>% 
  finalize_workflow(knn_min19)
knn_fit19 <- 
  final_knn_wf19 %>% 
  last_fit(split = spring_19_split)
knn_fit19 %>% collect_metrics()

# predictions
knn_results19 <- 
  knn_fit19 %>% 
  collect_predictions()
# view results
knn_results19

# KNN Graphically
knn_results19 %>%
  ggplot(aes(.pred, total_amount)) +
  geom_abline(lty = 2, color = "black", size = 1) +
  geom_point(alpha = 0.5, color = "dark green") +
  labs(
    title = 'KNN Regression Results',
    x = "Truth",
    y = "Predicted total amount",
    color = NULL
  ) + 
  theme_ipsum()
```